= JBake Maven Plugin
Jonathan Bullock
2021-04-20
:idprefix:

JBake Maven Plugin is a Maven plugin allowing you to integrate http://jbake.org[JBake] into your projects build. This is the official version published at
the following Maven coordinates:

----
<dependency>
    <groupId>org.jbake</groupId>
    <artifactId>jbake-maven-plugin</artifactId>
    <version>...</version>
</dependency>
----

The JBake Maven Plugin version now matches the JBake version.

Special thanks must go to the original author of this plugin - https://github.com/aldrinleal[Aldrin Leal].

== Usage

To use JBake Maven Plugin in your build add the plugin into your pom.xml as shown below:

----
<build>
...
    <plugins>
    ...
        <plugin>
            <groupId>org.jbake</groupId>
            <artifactId>jbake-maven-plugin</artifactId>
            <version>...</version><!-- Same version as JBake -->
            <configuration>
                <!--<inputDirectory>${project.basedir}/src/main/resources</inputDirectory>-->
                <!--<outputDirectory>${project.build.directory}/classes</outputDirectory>-->
            </configuration>
            <executions>
                <execution>
                    <id>default-generate</id>
                    <phase>generate-resources</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
       ...
    </plugins>
...
</build>
----

=== Dependencies

The plugin automatically includes all optional dependencies of `jbake-core`,
including freemarker, thymeleaf, asciidoctor, flexmark (markdown), etc.
This makes it easy to get started with the plugin.
It also reduces maintenance when upgrading to a new JBake version,
because you don't need to align the versions of freemarker, thymeleaf, asciidoctor, flexmark, etc.

However, if you want your build to only download the bare minimum it needs,
you can use `<exclusions>` to exclude the dependencies you don't need.

An example of the plugin being used can be found in this project: https://github.com/jonbullock/maven-jbake-site[https://github.com/jonbullock/maven-jbake-site]

== Goals

There are 4 goals provided by this plugin:

* `jbake:seed` - seeds your project/site with example content and templates
* `jbake:generate` - bakes your project/site
* `jbake:watch` - watches to changes and bakes your site whenever a change is detected
* `jbake:inline` - bakes, watches and serves out content on http://localhost:8820[http://localhost:8820]

You can also more details on each goal by running the help goal:

----
$ mvn jbake:help -Ddetail # -DgoalName=[seed|generate|watch|inline]
----

== Versioning

The project adopts the http://semver.org[Semantic Versioning] spec to maintain an understandable backwards compatibility strategy.

The version format is as follows:

----
<major>.<minor>.<patch>-<label>
----

* An increment of the major version represents incompatible API changes.
* An increment of the minor version represents additional functionality in a backwards-compatible manner.
* An increment of the patch version represents backwards-compatible bug fixes.
* Existence of a label represents a pre-release or build metadata.

== Copyright & License

This plugin is licensed under the Apache 2.0 License.
JBake itself is licensed under the MIT license.
