= JBake
Ondrej Zizka, Jonathan Bullock
2025-12-01
:idprefix:

http://jbake.org[JBake] is a Java based open source static site/blog generator for developers.

NOTE: This is a fork maintained by Ondrej Zizka with modernizations including Kotlin 2.2, Gradle 9, JDK 17+, and Maven build support.

image:https://img.shields.io/github/v/release/OndraZizka/jbake?label=download&sort=semver["GitHub Release Download", link="https://github.com/OndraZizka/jbake/releases/latest"]
image:https://img.shields.io/maven-central/v/ch.zizka.jbake/jbake-core.svg["Maven Central", link="https://central.sonatype.com/artifact/ch.zizka.jbake/jbake-core"]

*Version:* 5.0.0-rc1 | *Group ID:* `ch.zizka.jbake`

== Documentation

Original documentation is available on http://jbake.org/docs/[jbake.org].

Additional documentation for this fork:

* link:BUILD.adoc[Build Guide] - Information on building with Gradle or Maven
* link:docs/releasing/RELEASING.md[Release Guide] - Instructions for publishing to Maven Central
* link:CONTRIBUTING.asciidoc[Contributing Guide]

== Contributing

We welcome all contributions to the project both big and small. From new features, bug reports to even spelling mistake corrections in
the documentation. Please don't hesitate to submit an issue.

The link:CONTRIBUTING.asciidoc[Contributing] guide provides information on how to submit an issue or create a pull request to fix a bug or
add a new feature to JBake.

== Versioning

The project has adopted the http://semver.org[Semantic Versioning] spec from v2.2.0 onwards to maintain an
understandable backwards compatibility strategy.

The version format is as follows:

----
<major>.<minor>.<patch>-<label>
----

* An increment of the major version represents incompatible API changes.
* An increment of the minor version represents additional functionality in a backwards-compatible manner.
* An increment of the patch version represents backwards-compatible bug fixes.
* Existence of a label represents a pre-release or build metadata.

== Community

Talk to the developers behind JBake:

* http://groups.google.com/group/jbake-dev[Mailing list]
* link:irc://irc.freenode.net/#jbake[IRC - #jbake on Freenode]

Talk to other users of JBake on the forum:

* http://groups.google.com/group/jbake-user[Forum]

== Docker Image

The image uses https://hub.docker.com/_/gradle[gradle:9.2.1-jdk17] for building a distribution of JBake and
https://hub.docker.com/_/eclipse-temurin[eclipse-temurin:17-jre-alpine] for runtime.

=== Build

To build the Docker image:

----
$ docker build -t jbake/jbake:latest .
----

=== Usage

To execute JBake via Docker run this from project directory:

----
$ docker run --rm -u jbake -v "$PWD":/mnt/site jbake/jbake:latest
----

This command will execute using the jbake user to avoid running as root and will mount the current working directory as `/mnt/site`
in the Docker container where JBake is expecting your project files to be. By default the Docker image will execute a bake `-b` only.

If you want to bake and serve your project using the Docker image then you'll need to override the default command:

----
$ docker run --rm -u jbake -v "$PWD":/mnt/site -p 8820:8820 jbake/jbake:latest -b -s
----

This command will also expose port 8820 from the container, you'll also need to set the following option in your `jbake.properties` file:

----
server.hostname=0.0.0.0
----

NOTE: Docker image timezone is _UTC_. This may affect the date and time expected in output content. To set different timezone, add `TZ` environment variable and set value to required https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[timezone^]. Example - `docker run --rm -u jbake  -e TZ=America/New_York -v "$PWD":/mnt/site jbake/jbake:latest`


== Build System

This project supports both http://gradle.org[Gradle] 9+ and https://maven.apache.org[Maven] as build systems.

=== Building with Gradle

To build the JBake distribution ZIP file:

----
$ ./gradlew distZip
----

This will build a ZIP file in the `jbake-dist/build/distributions` folder.

=== Building with Maven

To build the project with Maven:

----
$ export JAVA_HOME=/path/to/jdk-17
$ mvn clean install
----

For more information see link:BUILD.adoc[Build Guide]

== Coding conventions

The project uses a basic set of http://checkstyle.sourceforge.net/[checkstyle] rules to keep the Code in shape.

We configured the gradle checkstyle Plugin to run with the `check` task.
It does not break the build if convention violations are found. But prints a warning and generates a report.

For more information see link:BUILD.adoc[Test, Build and Deploy]

=== Setup Intellij

* Install https://github.com/jshiell/checkstyle-idea[checkstyle-idea plugin]
+
Settings -> Plugins -> CheckStyle-IDEA

* Configure
+
Settings -> Other Settings -> Checksytle
+
Add a new _Configuration File_.
Enter a Description like "jbake Checkstyle" and choose "Use a local Checkstyle file".
The checkstyle File is located at the project root path `config/checkstyle/checkstyle.xml`

* Add to Editor Code Style Scheme
+
Settings -> Editor -> Code Style
+
Click the gear Symbol besides the "Scheme:" drop-down.
+
Import Scheme -> Checkstyle Configuration
+
Pick the project checkstyle file `config/checkstyle/checkstyle.xml`

== Tools & Libraries Used

=== Platform & Core

* https://kotlinlang.org/[Kotlin 2.2] - Primary programming language
* https://www.oracle.com/java/technologies/downloads/#java17[JDK 17+] - Java Development Kit
* http://commons.apache.org/proper/commons-configuration/[Apache Commons Configuration] - Configuration management
* https://logback.qos.ch/[Logback] & https://www.slf4j.org/[SLF4J] - Logging framework
* http://args4j.kohsuke.org/[Args4j] - Command-line argument parsing
* http://www.eclipse.org/jetty/[Jetty Server] - Embedded web server
* http://www.orientdb.org/[OrientDB] - Document database for content storage

=== Templating Engines

* http://freemarker.org/[Freemarker] - Template engine
* http://groovy-lang.org/[Groovy] - Groovy templates support
* https://www.thymeleaf.org/[Thymeleaf] - Modern server-side Java template engine
* https://github.com/jknack/handlebars.java[Handlebars.java] - Handlebars template engine

=== Content Parsing & Processing

* http://asciidoctor.org/[AsciidoctorJ] - AsciiDoc processor
* https://github.com/vsch/flexmark-java[Flexmark] - Markdown parser and processor
* https://commonmark.org/[CommonMark] - Markdown specification implementation

=== Build Systems

* https://maven.apache.org/[Maven] - Primary build system for multi-module projects
* http://gradle.org[Gradle 9] - Alternative build system with Kotlin DSL support
* https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper] - Version-locked Gradle distribution

=== Testing

* https://kotest.io/[Kotest] - Kotlin testing framework
* http://junit.org/[JUnit 5] - Java testing framework
* https://mockk.io/[MockK] - Mocking library for Kotlin
* https://site.mockito.org/[Mockito] - Mocking framework for Java
* https://www.testcontainers.org/[Testcontainers] - Docker-based integration testing
* https://assertj.github.io/doc/[AssertJ] - Fluent assertions library

== Copyright & License

Licensed under the MIT License, see the link:LICENSE[LICENSE] file for details.
