= JBake
Jonathan Bullock
2013-10-20
:idprefix:

== JBake

http://jbake.org[JBake] is a Java based open source static site/blog generator for developers.

image:http://img.shields.io/travis/jbake-org/jbake/master.svg["Build Status", link="https://travis-ci.org/jbake-org/jbake"]
image:http://img.shields.io/coveralls/jbake-org/jbake/master.svg["Coverage Status", link="https://coveralls.io/r/jbake-org/jbake"]

== Documentation

Full documentation is available on http://jbake.org/docs/[jbake.org].

== Contributing

We welcome all contributions to the project both big and small. From new features, bug reports to even spelling mistake corrections in 
the documentation. Please don't hesitate to submit an issue.

The link:CONTRIBUTING.asciidoc[Contributing] guide provides information on how to submit an issue or create a pull request to fix a bug or 
add a new feature to JBake.

== Versioning

The project has adopted the http://semver.org[Semantic Versioning] spec from v2.2.0 onwards to maintain an 
understandable backwards compatibility strategy.

The version format is as follows:

----
<major>.<minor>.<patch>-<label>
----

* An increment of the major version represents incompatible API changes.
* An increment of the minor version represents additional functionality in a backwards-compatible manner.
* An increment of the patch version represents backwards-compatible bug fixes.
* Existence of a label represents a pre-release or build metadata.

== Community

Talk to the developers behind JBake:

* http://groups.google.com/group/jbake-dev[Mailing list]
* link:irc://irc.freenode.net/#jbake[IRC - #jbake on Freenode]

Talk to other users of JBake on the forum:

* http://groups.google.com/group/jbake-user[Forum]

== Build System

The project uses Apache Maven as the build system. To build the JBake distribution ZIP file execute the following command from the root of the repo:

----
$ mvn package
----

This will build a ZIP file in the `/dist` folder.

Alternatively you can run directly from the source code using the Maven exec plugin:

----
$ mvn exec:java -Dexec.mainClass=org.jbake.launcher.Main -Dexec.args="/fromFolder /tmp/toFolder/"
----

== Tools & Libraries Used

* http://commons.apache.org/[Apache Commons IO, Configuration, Lang & Logging]
* http://maven.apache.org/[Apache Maven]
* http://args4j.kohsuke.org/[Args4j]
* http://asciidoctor.org/[AsciidoctorJ]
* http://www.eclipse.org/[Eclipse IDE]
* http://freemarker.org/[Freemarker]
* http://junit.org/[JUnit]
* http://pegdown.org/[Pegdown]
* http://www.eclipse.org/jetty/[Jetty Server]
* http://www.orientdb.org/[OrientDB]
* http://groovy-lang.org/[Groovy]

== Copyright & License

Licensed under the MIT License, see the link:LICENSE[LICENSE] file for details.
