= JBake Maven Plugin
Jonathan Bullock
2018-04-23
:idprefix:

image:https://maven-badges.herokuapp.com/maven-central/org.jbake/jbake-maven-plugin/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/org.jbake/jbake-maven-plugin"]

JBake Maven Plugin is a Maven plugin allowing you to integrate http://jbake.org[JBake] into your projects build. This is the official version published at 
the following Maven coordinates:

----
<dependency>
    <groupId>org.jbake</groupId>
    <artifactId>jbake-maven-plugin</artifactId>
    <version>0.3.2</version>
</dependency>
----

Special thanks must go to the original author of this plugin - https://github.com/aldrinleal[Aldrin Leal].

== Goals

There are 4 goals provided by this plugin:

* `jbake:seed` - seeds your project/site with example content and templates
* `jbake:generate` - bakes your project/site
* `jbake:watch` - watches to changes and bakes your site whenever a change is detected
* `jbake:inline` - bakes, watches and serves out content on http://localhost:8080[http://localhost:8080]

You can also more details on each goal by running the help goal:

----
$ mvn jbake:help -Ddetail # -DgoalName=[seed|generate|watch|inline]
----

== Versioning

The project adopts the http://semver.org[Semantic Versioning] spec to maintain an understandable backwards compatibility strategy.

The version format is as follows:

----
<major>.<minor>.<patch>-<label>
----

* An increment of the major version represents incompatible API changes.
* An increment of the minor version represents additional functionality in a backwards-compatible manner.
* An increment of the patch version represents backwards-compatible bug fixes.
* Existence of a label represents a pre-release or build metadata.

== Copyright & License

This plugin is licensed under the Apache 2.0 License.
