language: java

jdk: openjdk8

install: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2/
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  - ./gradlew --version

script: ./gradlew build -S

env: TERM=dumb
