#!/bin/bash

P=$(realpath $0 2>/dev/null)
if [ 0 -ne $? ]; then
  P=$0
fi

EXEC_LOC="`dirname "$P"`"
EXEC_PARENT="`dirname $EXEC_LOC`"

CYGWIN=false;
case "`uname`" in
  CYGWIN*) CYGWIN=true;;
esac

if $CYGWIN ;
then
    java -jar $(cygpath -w "${EXEC_PARENT}/jbake-core.jar") $@
else
    java -jar "${EXEC_PARENT}/jbake-core.jar" $@
fi